use invulnerable hz and mc version
hazelcast/hazelcast-platform-operator-docs pull request #13
Opened 2022-01-04 14:15 UTC by hasancelik

2022-01-04 14:57 UTC, JakeSCahill requested changes
There's no need to update these attributes for patch versions. The major.minor version of the docs is for the latest patch.

2022-01-05 15:22 UTC, JakeSCahill approved these changes

2022-01-06 17:39 UTC, JakeSCahill commented
Will you backport the code comment to #14 ?

2022-01-19 09:29 UTC, hasancelik commented
> Will you backport the code comment to #14 ?

I think we do not need to backport it because the note/reminder is for us actually. We will not touch/maintain 5.0 branch again.

2022-01-19 09:29 UTC, merged