Add WanSync docs [CN-369]
hazelcast/hazelcast-platform-operator-docs pull request #152
Opened 2024-01-18 15:53 UTC by SeriyBg

2024-01-19 09:17 UTC, rebekah-lawrence requested changes

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +:description: pass:q[WAN Syncronization allows you to overcome this out-of-sync issues with the WAN replicated data. ]
```suggestion
:description: pass:q[WAN Syncronization allows you to overcome out-of-sync issues with the WAN replicated data. ]
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +Before you create and configure a `WanSync` resource, you need to create the following:
```suggestion
Before you create and configure a `WanSync` resource, you must create the following:
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +To configure WAN Syncronization, you need to create `WanSync` resource. For more detailed information, see the xref:api-ref.adoc#wansyncspec[API Reference].
```suggestion
To configure WAN Syncronization, you must create `WanSync` resource. For more detailed information, see the xref:api-ref.adoc#wansyncspec[API Reference].
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +There are two ways to create a `WanSync` resource. The first one is by spcifying the existing `WanReplication` name. This way, the `WanSync` will reuse the existing and running WAN replication procce
```suggestion
There are two ways to create a `WanSync` resource. The first one is by specifying the existing `WanReplication` name. This means that the `WanSync` reuses the existing and running WAN replication process.
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +NOTE: For using this appoach, you must make sure that the `WanReplication` resource is succesully created.
```suggestion
NOTE: For this approach, you must make sure that the `WanReplication` resource is successfully created.
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +Another apporach is to specify the WAN replication configuration directly in the `WanSync` resource. This way, the operator will create a new `WanReplication` resource before running the WAN syncroni
```suggestion
Another approach is to specify the WAN replication configuration directly in the `WanSync` resource. This means that the operator creates a new `WanReplication` resource before running the WAN syncronization process. The created `WanReplication` is deleted when the corresponding `WanSync` is deleted.
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +After creating the `WanSync` resource, run the following command to find out the WAN syncronization status:
```suggestion
After creating the `WanSync` resource, run the following command to see the WAN syncronization status:
```

2024-01-19 09:17 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/wan-sync.adoc
> +You should see the following output:
```suggestion
The output is similar to the following:
```

2024-01-19 16:52 UTC, rebekah-lawrence approved these changes
LGTM

2024-01-23 10:45 UTC, cagric0 approved these changes

2024-01-25 08:25 UTC, Serdaro approved these changes

2024-01-25 09:29 UTC, semihbkgr approved these changes

2024-01-31 09:59 UTC, cheels commented on docs/modules/ROOT/examples/wan-sync-full.yaml
> +  wanReplicationName: wan-replication-sample
Here should be **wanReplicationResourceName**

2024-01-31 14:11 UTC, cheels approved these changes

2024-02-01 10:19 UTC, merged