Add CP Subsystem documentation [CN-1149]
hazelcast/hazelcast-platform-operator-docs pull request #170
Opened 2024-02-27 13:12 UTC by SeriyBg

2024-02-27 13:25 UTC, rebekah-lawrence requested changes

2024-02-27 13:25 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/cp-subsystem.adoc
> +To enable CP Subsystem you need to configure the `cpSubsystem` section in the Hazelcast CR.
```suggestion
To enable CP Subsystem you must configure the `cpSubsystem` section in the Hazelcast custom resource.
```

2024-02-27 13:25 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/cp-subsystem.adoc
> +When enableing CP subsystem, it will always enable the CP Subsystem Persistence. Therefore, CP Subsystem requires a PVC to be configured.
```suggestion
When CP subsystem is enabled, it always enables CP Subsystem Persistence. This means that a PVC must be configured before enabling CP Subsystem.
```

2024-02-27 13:25 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/cp-subsystem.adoc
> +When the the `pvc` section is configured in `cpSubsystem`, the new PVC will created and mounted for the CP Subsystem. However, the same PVC can be used for both xref:backup-restore.adoc[Persistence]
```suggestion
When the `pvc` section is configured in `cpSubsystem`, a PVC is created and mounted for the CP Subsystem. If you want to use the same PVC for both xref:backup-restore.adoc[Persistence] and CP Subsytem, configure the Persistence but do not configure `pvc` for the CP Subsystem.
```

2024-02-27 14:09 UTC, rebekah-lawrence approved these changes
LGTM

2024-02-28 16:08 UTC, kutluhanmetin approved these changes
LGTM

2024-03-21 15:10 UTC, merged