[CN-1163] Restriction warning on restoring from local backup
hazelcast/hazelcast-platform-operator-docs pull request #181
Opened 2024-03-14 11:31 UTC by semihbkgr

2024-03-14 11:53 UTC, rebekah-lawrence requested changes

2024-03-14 11:53 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/backup-restore.adoc
> +WARNING: Local backups are supported to be restored only once.
```suggestion
Note: You can only use a local backup once to restore a cluster.
```

2024-03-14 12:14 UTC, semihbkgr commented on docs/modules/ROOT/pages/backup-restore.adoc
> +WARNING: Local backups are supported to be restored only once.
`note` would fit better, thanks 👍

2024-03-20 08:06 UTC, rebekah-lawrence approved these changes
LGTM

2024-03-27 09:41 UTC, hasancelik approved these changes

2024-03-27 09:59 UTC, merged