[CN-1000] Add Tiered Storage page
hazelcast/hazelcast-platform-operator-docs pull request #185
Opened 2024-03-25 10:52 UTC by cagric0

2024-03-25 13:09 UTC, rebekah-lawrence requested changes

2024-03-25 13:09 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/tiered-storage.adoc
> +- Data Persistence and Tiered Storage are mutually exclusive features. Both can not be enabled simultaneously. *PersistenceEnabled* must be false.
```suggestion
- Data Persistence and Tiered Storage are mutually exclusive features; you cannot enable both simultaneously. *PersistenceEnabled* must be false when using Tiered Storage.
```

2024-03-25 13:18 UTC, cagric0 commented on docs/modules/ROOT/pages/tiered-storage.adoc
> +For each given local device configuration, *clusterSize*(3) PVCs will be created and used as local disk.
You are right. It's confusing but let me explain what I want to say and you can help me. User can configure multiple local devices in a Hazelcast CR. Separate PVCs will be created for each local devices and they will be used as local disk. The number of created PVCs will be equal to cluster size for each local device. Let's say we have configured 2 local devices called `device1` and `device2`. Hazelcast CR name is `hazelcast`, and cluster size is `3`. In this case we will have 6 PVCs total. 

PVC list:
device1-hazelcast-0
device1-hazelcast-1
device1-hazelcast-2
device2-hazelcast-0
device2-hazelcast-1
device2-hazelcast-2

Basically for each member and device combination, we will have separate PVCs.

2024-03-25 13:43 UTC, rebekah-lawrence reviewed
Is this clearer? Your example works really well to explain it; always good to include this level of information it can really help people (and I'm sure it won't just be me!).

2024-03-25 13:43 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/tiered-storage.adoc
> +For each given local device configuration, *clusterSize*(3) PVCs will be created and used as local disk.
Thank you, that helps - and I'd suggest keeping the example; new suggestion below

2024-03-25 13:43 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/tiered-storage.adoc
> +For each given local device configuration, *clusterSize*(3) PVCs will be created and used as local disk.
You can configure one or more local devices in a single Hazelcast CR. A separate PVC is created for each local device and is used as the local disk for that device. Therefore, the number of created PVCs matches the cluster size for each configured local device. 

For example, if we create two local devices, called device1 and device2, for a Hazelcast CR, called hazelcast, and we have a cluster size of `3`, a total of six PVCs are created as follows:

* device1-hazelcast-0
* device1-hazelcast-1
* device1-hazelcast-2
* device2-hazelcast-0
* device2-hazelcast-1
* device2-hazelcast-2

2024-04-03 07:35 UTC, Serdaro reviewed
Minor suggestions.

2024-04-03 07:35 UTC, Serdaro commented on docs/modules/ROOT/pages/tiered-storage.adoc
> +- Configured local device size (*LocalDevice.PVC.RequestStorage*) must be higher than *MemoryCapacity*.
```suggestion
- Configured local device size on the Hazelcast CR (*LocalDevice.PVC.RequestStorage*) must be higher than *MemoryCapacity* on the Map CR.
```

2024-04-04 10:02 UTC, Serdaro approved these changes
Approving with this minor clarification.

2024-04-04 10:02 UTC, Serdaro commented on docs/modules/ROOT/pages/tiered-storage.adoc
> +- Native Memory size(*NativeMemory.Size*) must be higher than sum of all *MemoryCapacity*
```suggestion
- Native Memory size (*NativeMemory.Size*) on the Hazelcast CR must be higher than the sum of memory capacities (*TieredStore.MemoryCapacity*) on all Map CRs.
```

2024-04-04 10:30 UTC, hasancelik approved these changes

2024-04-04 10:30 UTC, merged