Update get-started.adoc
hazelcast/hazelcast-platform-operator-docs pull request #198
Opened 2024-04-22 17:11 UTC by cheels

Add more clarification in documentation related to Restricted Installation

2024-04-23 07:08 UTC, SeriyBg approved these changes

2024-04-23 07:18 UTC, rebekah-lawrence requested changes

2024-04-23 07:18 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/get-started.adoc
> +<1> Disabling `createClusterScopedResources` confines the operator to manage resources only within the specified namespaces, enhancing security and compliance.
```suggestion
<1> Disabling `createClusterScopedResources` means that the management of resources by Operator is constrained to specified namespaces. This enhances both security and compliance.
```

2024-04-23 07:18 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/get-started.adoc
> +<2> `webhook.enabled=false` is necessary because enabling webhooks requires cluster-wide permissions, which conflicts with our restrictions against cluster-scoped resource creation.
```suggestion
<2> Disabling `webhook.enabled` means that webhooks cannot be used. This is needed as the cluster-wide permissions required for webhooks conflict with our restrictions on cluster-scoped resource creation.
```

2024-04-23 07:18 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/get-started.adoc
> +<3> By setting `enableHazelcastNodeDiscovery` to false, the operator will not automatically discover nodes across all namespaces. This limits the use of `NODE_AWARE` in `highAvailabilityMode` and `No
```suggestion
<3> Disabling `enableHazelcastNodeDiscovery` means that Operator does not automatically discover nodes across all namespaces. This limits the use of `NODE_AWARE` in `highAvailabilityMode` and of `NodePort` in `discoveryServiceType`, both of which depend on broader node discovery.
```

2024-04-24 09:04 UTC, cagric0 approved these changes

2024-04-24 09:05 UTC, rebekah-lawrence approved these changes
LGTM

2024-04-24 09:42 UTC, merged