[CN-1261]: Add docs for lite members
hazelcast/hazelcast-platform-operator-docs pull request #205
Opened 2024-05-13 08:37 UTC by kutluhanmetin

2024-05-13 08:43 UTC, rebekah-lawrence requested changes

2024-05-13 08:43 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/lite-members.adoc
> +To be able to enable lite members Hazelcast Platform Operator accepts a parameter `liteMemberCount` in Hazelcast CR configuration.
```suggestion
To enable lite members, set the `liteMemberCount` parameter in the Hazelcast CR configuration.
```

2024-05-13 08:43 UTC, rebekah-lawrence commented on docs/modules/ROOT/pages/lite-members.adoc
> +There are some limitations while setting `liteMemberCount`:
```suggestion
Bear in mind the following limitations while setting `liteMemberCount`:
```

2024-05-14 13:52 UTC, cagric0 approved these changes

2024-07-17 10:33 UTC, closed without merging