[CN-1326]: add supported platform versions page
hazelcast/hazelcast-platform-operator-docs pull request #220
Opened 2024-07-11 14:00 UTC by kutluhanmetin

2024-07-11 14:25 UTC, hasancelik requested changes

2024-07-11 14:25 UTC, hasancelik commented on docs/modules/ROOT/pages/kubernetes-platform-support.adoc
> +== Supported OCP Versions
```suggestion
== Supported OpenShift Versions
```

2024-07-11 14:25 UTC, hasancelik commented on docs/modules/ROOT/pages/kubernetes-platform-support.adoc
> += Supported Platform Versions
I think we can move this one to the Overview page:
https://docs.hazelcast.com/operator/latest/
before `Community support` section:
https://docs.hazelcast.com/operator/latest/#community-support

2024-07-12 11:42 UTC, hasancelik requested changes

2024-07-12 11:42 UTC, hasancelik commented on docs/modules/ROOT/pages/index.adoc
> +=== Supported OCP Versions
```suggestion
=== OpenShift Versions
```

2024-07-12 11:42 UTC, hasancelik commented on docs/modules/ROOT/pages/index.adoc
> +Hazelcast Platform Operator supports following OCP versions:
```suggestion
Hazelcast Platform Operator supports following OpenShift versions:
```

2024-07-12 11:42 UTC, hasancelik commented on docs/modules/ROOT/pages/index.adoc
> +== Supported Platform Versions
```suggestion
== Supported Versions
```

2024-07-12 11:42 UTC, hasancelik commented on docs/modules/ROOT/pages/index.adoc
> +=== Supported Kubernetes Versions
```suggestion
=== Kubernetes Versions
```

2024-07-18 12:13 UTC, hasancelik approved these changes

2024-07-22 13:21 UTC, rebekah-lawrence approved these changes
LGTM

2024-07-22 13:31 UTC, merged