Introduce page for air-gapped env installation
hazelcast/hazelcast-platform-operator-docs pull request #250
Opened 2024-10-15 11:45 UTC by hasancelik

2024-10-15 13:03 UTC, amandalindsay requested changes
Just some minor docs tweaks and a question (I'm unfamiliar with the content) otherwise looks good

2024-10-15 13:03 UTC, amandalindsay commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +== Setting image for the Platform Operator
```suggestion
== Setting the image for the Platform Operator
```

2024-10-15 13:03 UTC, amandalindsay commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +== Setting image for the Hazelcast
```suggestion
== Setting the image for Hazelcast
```

2024-10-15 13:03 UTC, amandalindsay commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +== Setting image for the Sidecar Agent
```suggestion
== Setting the image for the Sidecar Agent
```

2024-10-15 13:03 UTC, amandalindsay commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +== Setting image for the Management Center
```suggestion
== Setting the image for the Management Center
```

2024-10-15 13:03 UTC, amandalindsay commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +== Setting image for the Flow
```suggestion
== Setting the image for Flow
```

2024-10-18 12:18 UTC, kutluhanmetin commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +By default, the Platform Operator, Hazelcast, the agent and Management Center image do not require you to specify the container images. The operator will automatically set the correct container image
```suggestion
By default, while using the Hazelcast Platform Operator, you don't need to specify the container images in Hazelcast and Management Center custom resources for any application. The operator automatically sets the correct container image for each application. When running in an air-gapped or offline environment, you have to mirror the official images in a private container image registry. To make use of your mirrored images, you have to set the image for each application explicitly, as shown in the preceding sections.
```

2024-10-18 12:22 UTC, kutluhanmetin commented on docs/modules/ROOT/pages/air-gapped-env.adoc
> +helm install operator hazelcast/hazelcast-platform-operator --version=5.13.0 \
```suggestion
helm install operator hazelcast/hazelcast-platform-operator --version={operator-chart-version} \
```

2024-10-21 12:50 UTC, kutluhanmetin approved these changes

2024-10-21 12:55 UTC, amandalindsay approved these changes

2024-10-21 12:58 UTC, merged