[CN-396] Update doc for B&R with external storage
hazelcast/hazelcast-platform-operator-docs pull request #37
Opened 2022-06-09 09:20 UTC by cagric0

2022-06-09 13:29 UTC, hakanmemisoglu approved these changes

2022-06-09 13:29 UTC, hakanmemisoglu commented on docs/modules/ROOT/examples/hazelcast-persistence-restore.yaml
> +    version: 0.1.0
```suggestion
    version: 0.1.0

```

2022-06-09 13:29 UTC, hakanmemisoglu commented on docs/modules/ROOT/examples/hot-backup-agent.yaml
> +  secret: "br-secret-s3" <2>
```suggestion
  secret: "br-secret-s3" <2>
  
```

2022-06-09 13:29 UTC, hakanmemisoglu commented on docs/modules/ROOT/examples/hot-backup-agent.yaml
> +  secret: "br-secret-s3" <2>
```suggestion
  secret: "br-secret-s3" <2>
```
```suggestion
  secret: "br-secret-s3" <2>
  
```

2022-06-10 13:02 UTC, JakeSCahill requested changes
Would it make more sense to have this heading structure so that users can see what information is relevant depending on the Persistence option they choose to enable?

```
Enabling Local Persistence
      Triggering Local Backups
      Restoring from Local Backups
Enabling External Persistence
      Triggering External Backups
      Restoring from External Backups
```

Then we can remove this note, which is confusing in the current location:

> NOTE: Make sure to use external restore, when you decide to use external backup.

2022-06-10 13:02 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +The agent configuration is optional. If you give backupType as 'External' and do not pass the agent configuration, the operator
```suggestion
The agent configuration is optional. If you set the `backupType` to `External` and do not pass the agent configuration, the operator
```

2022-06-13 09:29 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +NOTE: You can <<status-backup, check the status of a Backup >> and <<schedule-backup, schedule external Backups >> same as the local ones
Maybe pull the status-backup and schedule-backup sections out of the local backup section and make them second-level headings?

2022-06-13 09:29 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +. First two steps will be the same with <<restore-local, Restoring from Local Backups>>: Deleting the Hazelcast cluster and Checking that the PVCs are still available
It's better to put the steps here rather than linking.

2022-06-13 09:34 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +For triggering external Backup, you need to pass two additional configurations.
```suggestion
To trigger an external backup, you need to pass two additional configurations.
```

2022-06-13 09:35 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +One is `bucketURI`. The other one is `secret`. According to chosen cloud provider you need to get
```suggestion
One is `bucketURI`. The other one is `secret`. According to your chosen cloud provider, you need to get
```

2022-06-13 09:42 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +bucket URI and credentials to create secret.
```suggestion
```

2022-06-13 09:46 UTC, JakeSCahill commented on docs/modules/ROOT/pages/backup-restore.adoc
> +NOTE: You can <<status-backup, check the status of a Backup >> and <<schedule-backup, schedule external Backups >> same as the local ones
I assume that it's not the exact same process for local and external: For external, you must have the bucket URI and secret configured? This isn't a very user-friendly way of presenting this information. Users should be able to see from the table of contents what information they need. The current table of contents would make it look like you can only schedule and check the status of local backups.

Maybe we need another level of heading:

Local Backups
External Backups
HostPath Backups

We can duplicate the status and scheduled sections for each one.

The first paragraph of each top-level should also answer the following questions:
- What is this backup option?
- Why would I want to use this option?

2022-06-13 11:56 UTC, dzeromski-hazelcast approved these changes

2022-06-13 15:53 UTC, merged