[CN-531] Add Topic CR documentation
hazelcast/hazelcast-platform-operator-docs pull request #53
Opened 2022-09-29 11:39 UTC by mtyazici

2022-10-11 14:12 UTC, mtyazici commented on docs/modules/ROOT/nav.adoc
> +* xref:topic-configuration.adoc[Configuring Topics]
sure :+1:

2022-10-12 10:10 UTC, angelasimms requested changes
Minor changes to text only.

2022-10-12 10:10 UTC, angelasimms commented on docs/modules/ROOT/pages/topic-configuration.adoc
> +|When true all nodes listening to the same topic get their messages in the same order.
```suggestion
|When true, all nodes listening to the same topic get their messages in the same order.
```

2022-10-12 10:10 UTC, angelasimms commented on docs/modules/ROOT/pages/topic-configuration.adoc
> +|When true enables multi-threaded processing of incoming messages, otherwise a single thread will handle all topic messages.
```suggestion
|When true, enables multi-threaded processing of incoming messages. Otherwise, a single thread handles all topic messages.
```

2022-10-12 10:10 UTC, angelasimms commented on docs/modules/ROOT/pages/topic-configuration.adoc
> +NOTE: Multi threading can not be enabled when global ordering is used.
```suggestion
NOTE: You cannot enable multi-threading when global ordering is in use.
```

2022-10-12 10:10 UTC, angelasimms commented on docs/modules/ROOT/pages/topic-configuration.adoc
> +The following `Topic` custom resource creates a Topic configuration for the `Hazelcast` custom resource that is defined in the `hazelcastResourceName` field.
```suggestion
The following `Topic` custom resource creates a topic configuration for the `Hazelcast` custom resource that is defined in the `hazelcastResourceName` field.
```

2022-10-12 10:13 UTC, JakeSCahill commented on docs/modules/ROOT/pages/topic-configuration.adoc
> += Configuring Topics
These are Hazelcast topics, not Kafka topics 😄

2022-10-13 08:51 UTC, angelasimms approved these changes
Looks fine to me. Thank you!

2022-10-14 06:53 UTC, merged