[CN-448] Update WAN replication page and sample yaml
hazelcast/hazelcast-platform-operator-docs pull request #54
Opened 2022-09-29 17:07 UTC by cagric0

2022-10-05 08:29 UTC, angelasimms requested changes
Just a couple of minor changes.

2022-10-05 08:29 UTC, angelasimms commented on docs/modules/ROOT/pages/wan-replication.adoc
> +:description: pass:q[WAN Replication allows you to keep Hazelcast clusters in sync across multiple sites or cloud deployments. In Hazelcast Platform Operator, you can create a `WanReplication` resour
```suggestion
:description: pass:q[WAN replication allows you to keep Hazelcast clusters in sync across multiple sites or cloud deployments. In Hazelcast Platform Operator, you can create a `WanReplication` resource to replicate multiple maps from multiple source clusters to a single target Hazelcast cluster. ]
```

2022-10-05 08:29 UTC, angelasimms commented on docs/modules/ROOT/pages/wan-replication.adoc
> +- `kind`: The kind of custom resource. Either `Map`(default) or `Hazelcast`. The kind `Hazelcast` leads to apply WAN replication to the all custom maps created under the given Hazelcast resource.
```suggestion
- `kind`: The type of custom resource. Either `Map`(default) or `Hazelcast`. Use the  `Hazelcast` kind to apply WAN replication to all custom maps created under the given `Hazelcast` resource.
```

2022-10-05 14:15 UTC, angelasimms requested changes
Sorry, just one final change. My mistake.

2022-10-05 14:15 UTC, angelasimms commented on docs/modules/ROOT/pages/wan-replication.adoc
> +|The list of the custom `Map` or `Hazelcast` resource to which WAN replication applies.
```suggestion
|The list of custom `Map` or `Hazelcast` resources to which WAN replication applies.
```

2022-10-06 10:30 UTC, angelasimms approved these changes
All looks good to me. Thank you!

2022-10-10 10:38 UTC, mtyazici approved these changes

2022-10-10 10:38 UTC, mtyazici commented on docs/modules/ROOT/pages/wan-replication.adoc
> +kubectl get wanreplication wanreplication-sample
```suggestion
kubectl get wanreplication wanreplication-sample -o wide
```

Or we can remove the `message` column from the output of this command.

2022-10-10 17:37 UTC, merged