[CN-672] Add page with Native Memory parameters
hazelcast/hazelcast-platform-operator-docs pull request #81
Opened 2023-02-07 21:22 UTC by dzeromski-hazelcast

2023-02-09 10:20 UTC, cagric0 approved these changes
LGTM, but I think you should also get a review from Angela.

2023-02-14 12:17 UTC, hasancelik approved these changes
LGTM 👍 as @cagric0 said, getting reviews from doc team would be good before the merge.

2023-02-14 17:55 UTC, angelasimms requested changes
I'm not sure about the introduction/description as I read had to read it a few times before I understood the advantages of a native memory store. I tried to reword but not sure if it is accurate.

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +:description: Native Memory Store is designed as a pluggable memory manager which enables multiple memory stores for different data structures. These memory stores are all accessible by a common acce
```suggestion
:description: The Native Memory Store is a pluggable memory manager. It allows you to set up different configurations, or stores, for your application’s data structures on a single JVM. These memory stores form part of a common access layer which scales up to use a configured amount of memory on the JVM.
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +This topic explains how to configure native memory. It also brings together example of how you can configure your data structure with Native Memory.
```suggestion
As well as providing more predictable application scaling, using a Native Memory Store boosts performance, reduces latency, and minimizes garbage collection pauses. 
```
If we change the title, I don't think the original sentence is needed.

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> += Native Memory
```suggestion
= Configuring the Native Memory Store
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +== Configuring Native Memory
```suggestion
== Configuring a Native Memory Store
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +Below are the configuration options for the Native Memory feature.
```suggestion
Below are the configuration options for the Native Memory Store.
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +| AllocatorType specifies one of 2 types of mechanism for allocating memory.
```suggestion
| Specifies the mechanism for allocating memory; either XXXX or XXXX.
```
It makes sense to give both options if they are available, and to explain what they are used for.

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +|MinBlockSize is the size of smallest block that will be allocated.
```suggestion
|Size of smallest block of memory to allocate.
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +|PageSize is the size of the page in bytes to allocate memory as a block.
```suggestion
|Size of the page in bytes to allocate as a block of memory.
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +|MetadataSpacePercentage defines percentage of the allocated native memory that is used for the metadata of other map components such as index (for predicates), offset, etc.
```suggestion
|Percentage of the allocated native memory that is used for the metadata of other map components such as index (for predicates), offset, etc.
```
What if the data structure isn't a map?

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +- Creates cluster with Native Memory and `POOLED` allocator enabled.
```suggestion
- Creates a cluster with `Native Memory` and the `POOLED` allocator enabled.
```

2023-02-14 17:55 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +- Configures Map for that cluster that is using Native Memory.
```suggestion
- Configures a map on the cluster to use native memory.
```

2023-02-16 15:36 UTC, angelasimms requested changes

2023-02-16 15:36 UTC, angelasimms commented on docs/modules/ROOT/pages/native-memory.adoc
> +| Specifies the mechanism for allocating memory; either XXXX or XXXX.
For this line, you need to add in the name of the two allocator types. It looks like the first is `POOLED` but I'm not sure about the second one.

2023-02-20 12:11 UTC, merged