[CN-799]: Add doc for jet engine configuration
hazelcast/hazelcast-platform-operator-docs pull request #99
Opened 2023-03-29 08:52 UTC by kutluhanmetin

2023-04-26 10:38 UTC, cagric0 approved these changes

2023-04-26 14:33 UTC, cagric0 requested changes
I left two suggestion. Other than that LGTM

2023-04-26 14:33 UTC, cagric0 commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +== Enabling Jet Engine
```suggestion
== Configuring the Jet Engine
```
I would use `Configuring` to be consistent with other pages

2023-04-26 14:33 UTC, cagric0 commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +== Configuration Options
```suggestion
```
Same for here, I would remove this line to be consistent with other doc pages

2023-04-27 08:09 UTC, cagric0 approved these changes

2023-04-27 15:33 UTC, angelasimms requested changes
Just a few suggestions.

2023-04-27 15:33 UTC, angelasimms commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +:description: This section describes Hazelcast’s Jet engine specific configuration using Hazelcast Platform Operator.
```suggestion
:description: You can configure Hazelcast’s Jet engine using the Hazelcast Platform Operator.
```

2023-04-27 15:33 UTC, angelasimms commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +When you run Hazelcast using Platform Operator, Jet Engine is enabled by default.
```suggestion
The Jet engine is enabled by default and has the following configuration options.
```
As we're in the Operator docs, I don't think we need to repeat Hazelcast Platform Operator.

2023-04-27 15:33 UTC, angelasimms commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +|When true, enables resource uploading for Jet jobs.
```suggestion
|Set to `true` to enable the uploading of resources for Jet jobs.
```

2023-04-27 15:33 UTC, angelasimms commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +|The number of synchronous backups to configure on the IMap that Jet needs internally to store job metadata and snapshots.
```suggestion
|The number of synchronous backups to configure on the IMap, which Jet needs internally to store job metadata and snapshots.
```

2023-04-27 15:33 UTC, angelasimms commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +|Specifies whether the Lossless Cluster Restart feature is enabled.
```suggestion
|Whether the Lossless Cluster Restart feature is enabled.
```

2023-04-27 15:33 UTC, angelasimms commented on docs/modules/ROOT/pages/jet-engine-configuration.adoc
> +|Specifies the maximum number of records that can be accumulated by any single processor instance.
```suggestion
|The maximum number of records that can be accumulated by any single processor instance.
```

2023-04-27 17:19 UTC, angelasimms approved these changes
LGTM

2023-04-27 19:17 UTC, merged